version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "menu"
    ports:
      - "3307:3306"
    volumes:
      - /home/dev/Docker/Volumes/MySql:/var/lib/mysql